### PR TITLE
Fixed an old Gens bug with savestate colors

### PR DESCRIPTION
**Pull request by lab313ru**
Colors were swapped.

### CODE REVIEW

**Comment by hegyak** [comment]
What does this correct?

**Comment by DrMefistO** [comment]
When you're using the GSavestate program, bytes of CRAM colors are swapped in it. This commit fixes that, so you'll see normal colors in savestates.

**Comment by vadosnaprimer** [comment]
Does it make old savestates incompatible/broken?

**Comment by DrMefistO** [comment]
I think, all colors in old savestates will be swapped after that.

**Comment by marzojr** [comment]
This REALLY should not have commits 9962f49 and 86c1407; there is already a pull request for them. I am recommending to reject this unless these commits are removed.

**Comment by vadosnaprimer** [comment]
Yeah, otherwise it's probably alright to merge, since states remain working overall, and even *that* is from time to time broken by development, and people have to deal with it.

**Comment by marzojr** [comment]
I cherry-picked the savestate fix; so closed by 9b6c5420a34b079e5b8de35611e18a98490d2df2.

**Pull request closed without merging**
